import { useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../api';
import { useAuth } from '../contexts/AuthContext';
import PageHero from '../components/PageHero';
export default function AccountPage() {
  const { user, updateProfile } = useAuth(); const [form, setForm] = useState({ fullName: user.fullName || '', phone: user.phone || '', address: { line1: user.address?.line1 || '', line2: user.address?.line2 || '', city: user.address?.city || '', postcode: user.address?.postcode || '', country: user.address?.country || 'United Kingdom' } }); const [passwords, setPasswords] = useState({ currentPassword: '', newPassword: '' }); const [feedback, setFeedback] = useState({ type: '', text: '' });
  const save = async (event) => { event.preventDefault(); try { const data = await updateProfile(form); setFeedback({ type: 'success', text: data.message }); } catch (e) { setFeedback({ type: 'error', text: e.message }); } };
  const changePassword = async (event) => { event.preventDefault(); try { const data = await api('/auth/password', { method: 'PUT', body: passwords }); setFeedback({ type: 'success', text: data.message }); setPasswords({ currentPassword: '', newPassword: '' }); } catch (e) { setFeedback({ type: 'error', text: e.message }); } };
  const setAddress = (key, value) => setForm({ ...form, address: { ...form.address, [key]: value } });
  return <><PageHero eyebrow={user.customerId || user.role.toUpperCase()} title={`Hello, ${user.fullName}`} text="Manage your profile, saved delivery details and password." compact /><section className="section"><div className="container account-grid"><nav className="account-nav"><Link className="active" to="/account">Profile</Link><Link to="/orders">Order history</Link><Link to="/wishlist">Wishlist</Link><Link to="/shop">Continue shopping</Link>{user.role === 'admin' && <Link to="/admin">Admin dashboard</Link>}</nav><div>{feedback.text && <div className={`alert ${feedback.type}`}>{feedback.text}</div>}<form className="form-card" onSubmit={save}><h2>Profile details</h2><div className="form-grid"><label>Full name<input required value={form.fullName} onChange={(e) => setForm({ ...form, fullName: e.target.value })} /></label><label>Email address<input disabled value={user.email} /></label><label>Phone<input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></label><label>Address line 1<input value={form.address.line1} onChange={(e) => setAddress('line1', e.target.value)} /></label><label>Address line 2<input value={form.address.line2} onChange={(e) => setAddress('line2', e.target.value)} /></label><label>City<input value={form.address.city} onChange={(e) => setAddress('city', e.target.value)} /></label><label>Postcode<input value={form.address.postcode} onChange={(e) => setAddress('postcode', e.target.value)} /></label><label>Country<input value={form.address.country} onChange={(e) => setAddress('country', e.target.value)} /></label></div><button className="button primary" type="submit">Save profile</button></form><form className="form-card top-gap" onSubmit={changePassword}><h2>Change password</h2><div className="form-grid"><label>Current password<input type="password" required value={passwords.currentPassword} onChange={(e) => setPasswords({ ...passwords, currentPassword: e.target.value })} /></label><label>New password<input type="password" required minLength="8" value={passwords.newPassword} onChange={(e) => setPasswords({ ...passwords, newPassword: e.target.value })} /></label></div><button className="button secondary" type="submit">Update password</button></form></div></div></section></>;
}
