import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api, money } from '../api';
import PageHero from '../components/PageHero';
import Loading from '../components/Loading';
export default function DashboardPage() {
  const [data, setData] = useState(null); const [error, setError] = useState('');
  useEffect(() => { api('/dashboard').then(setData).catch((e) => setError(e.message)); }, []);
  const resources = [['products','Products & stock'],['categories','Categories'],['orders','Orders'],['users','Customers & roles'],['coupons','Coupons'],['reviews','Reviews'],['messages','Contact messages'],['subscriptions','Newsletter']];
  return <><PageHero eyebrow="ADMINISTRATION" title="StyleHaven dashboard" text="Database aggregation provides inventory, customer, fulfilment and revenue insights for decision making." compact /><section className="section"><div className="container admin-shell"><nav className="admin-nav"><Link className="active" to="/admin">Overview</Link>{resources.map(([key,label]) => <Link key={key} to={`/admin/${key}`}>{label}</Link>)}</nav><div className="admin-content">{error && <div className="alert error">{error}</div>}{!data ? <Loading label="Loading dashboard…" /> : <><div className="metric-grid"><article><span>Customers</span><strong>{data.metrics.customerCount}</strong></article><article><span>Active products</span><strong>{data.metrics.activeProductCount}</strong></article><article className={data.metrics.lowStockCount ? 'metric-warning' : ''}><span>Low stock</span><strong>{data.metrics.lowStockCount}</strong></article><article><span>All orders</span><strong>{data.metrics.orderCount}</strong></article><article><span>Awaiting action</span><strong>{data.metrics.pendingOrders}</strong></article><article><span>Revenue*</span><strong>{money(data.metrics.revenue)}</strong></article><article><span>Pending reviews</span><strong>{data.metrics.pendingReviews}</strong></article><article><span>New messages</span><strong>{data.metrics.newMessages}</strong></article></div><p className="small-note">*Demonstration revenue excludes cancelled orders and is not real income.</p><div className="dashboard-grid"><section className="panel"><h2>Order status breakdown</h2>{data.statusBreakdown.map((row) => <div className="bar-row" key={row.status}><span>{row.status}</span><div><i style={{ width: `${Math.max(8, row.count / Math.max(...data.statusBreakdown.map((x) => x.count)) * 100)}%` }} /></div><strong>{row.count}</strong></div>)}</section><section className="panel"><h2>Top products by units</h2>{data.topProducts.map((row) => <div className="rank-row" key={row._id}><div><strong>{row.name}</strong><span>{row.units} units</span></div><span>{money(row.sales)}</span></div>)}</section></div><section className="panel top-gap"><h2>Monthly sales insight</h2><div className="table-wrap"><table><thead><tr><th>Period</th><th>Orders</th><th>Revenue</th></tr></thead><tbody>{data.monthlySales.map((row) => <tr key={`${row.year}-${row.month}`}><td>{new Date(row.year, row.month-1).toLocaleString('en-GB',{month:'long',year:'numeric'})}</td><td>{row.orders}</td><td>{money(row.revenue)}</td></tr>)}</tbody></table></div></section></>}</div></div></section></>;
}
