import { useEffect,useState } from 'react';
import { Link } from 'react-router-dom';
import { api,imageUrl } from '../api';
import ProductCard from '../components/ProductCard';
import Loading from '../components/Loading';
export default function HomePage(){const[data,setData]=useState({categories:[],products:[],reviews:[]});const[loading,setLoading]=useState(true);useEffect(()=>{Promise.all([api('/categories'),api('/products?featured=true&limit=8'),api('/reviews')]).then(([c,p,r])=>setData({categories:c.categories,products:p.products,reviews:r.reviews.slice(0,3)})).finally(()=>setLoading(false));},[]);return <>
<section className="home-hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow">WEAR / LAYER / EXPRESS</p><h1>Modern clothing with clear size, colour and stock choices.</h1><p>Explore women’s and men’s clothing, outerwear and accessories. Every product, variant, price and availability figure is read from MongoDB.</p><div className="button-row"><Link className="button primary" to="/shop">Shop the collection</Link><Link className="button ghost light" to="/offers">View seasonal offers</Link></div><div className="hero-points"><span>✓ 30 database products</span><span>✓ Free delivery over £75</span><span>✓ Session bag and wishlist</span></div></div><div className="hero-art"><img src="/images/hero-clothing.jpg" alt="StyleHaven contemporary clothing collection"/><div className="hero-card"><strong>STYLE10</strong><span>10% off qualifying bags</span></div></div></div></section>
<section className="section"><div className="container section-heading"><div><p className="eyebrow">SHOP BY COLLECTION</p><h2>Find a look for every day</h2></div><Link to="/categories">View all collections →</Link></div>{loading?<Loading/>:<div className="container category-grid">{data.categories.map(c=><Link className="category-card" key={c._id} to={`/shop?category=${c.slug}`}><img src={imageUrl(c.image)} alt={c.name}/><div><h3>{c.name}</h3><p>{c.description}</p><span>Browse collection →</span></div></Link>)}</div>}</section>
<section className="section section-soft"><div className="container section-heading"><div><p className="eyebrow">FEATURED</p><h2>Popular StyleHaven pieces</h2></div><Link to="/shop">See all products →</Link></div>{loading?<Loading/>:<div className="container product-grid">{data.products.map(p=><ProductCard key={p._id} product={p}/>)}</div>}</section>
<section className="section"><div className="container promo-grid"><div className="promo-image"><img src="/images/about-showcase.jpg" alt="StyleHaven clothing display"/></div><div className="promo-copy"><p className="eyebrow">D1 DESIGN, D2 DATA</p><h2>The boutique experience now runs on MERN.</h2><p>The original StyleHaven branding, local images, collections, product details, wishlist and shopping-bag ideas are preserved. React renders the interface while Express, sessions and MongoDB manage the records and updates.</p><ul className="check-list"><li>Variant-level size and colour stock</li><li>Server-side cart and coupons</li><li>Real order records and order history</li><li>Administrator CRUD and analytics</li></ul><Link className="button secondary" to="/about">Read the project story</Link></div></div></section>
<section className="section section-dark"><div className="container section-heading light"><div><p className="eyebrow">CUSTOMER FEEDBACK</p><h2>Approved reviews from MongoDB</h2></div><Link to="/reviews">Read all reviews →</Link></div>{loading?<Loading/>:<div className="container review-grid">{data.reviews.map(r=><article className="review-card" key={r._id}><div className="stars">{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</div><p>“{r.text}”</p><strong>{r.name}</strong><span>{r.product?.name}</span></article>)}</div>}</section>
</>}
