import { useState } from 'react';
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import PageHero from '../components/PageHero';
export default function LoginPage() {
  const { user, login } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [form, setForm] = useState({ email: '', password: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  if (user) return <Navigate to={user.role === 'admin' ? '/admin' : '/account'} replace />;
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { const data = await login(form); navigate(location.state?.from || (data.user.role === 'admin' ? '/admin' : '/account'), { replace: true }); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const fill = (email, password) => setForm({ email, password });
  return <><PageHero eyebrow="ACCOUNT ACCESS" title="Login to StyleHaven" text="Login and logout are backed by secure server sessions stored in MongoDB." compact /><section className="section"><div className="container auth-layout"><form className="form-card" onSubmit={submit}><h2>Welcome back</h2><label>Email address<input type="email" required autoComplete="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>Password<input type="password" required autoComplete="current-password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></label>{error && <div className="alert error">{error}</div>}<button className="button primary full" type="submit" disabled={busy}>{busy ? 'Logging in…' : 'Login'}</button><p>New customer? <Link to="/signup">Create an account</Link></p></form><aside className="demo-card"><p className="eyebrow">ASSESSOR DEMO ACCOUNTS</p><h2>Use seeded credentials</h2><div><strong>Administrator</strong><code>admin@stylehaven.demo</code><code>Admin123!</code><button type="button" onClick={() => fill('admin@stylehaven.demo', 'Admin123!')}>Fill admin login</button></div><div><strong>Customer</strong><code>customer@stylehaven.demo</code><code>Customer123!</code><button type="button" onClick={() => fill('customer@stylehaven.demo', 'Customer123!')}>Fill customer login</button></div><p className="small-note">These accounts are only for assessment and demonstration.</p></aside></div></section></>;
}
