import { useEffect, useState } from 'react';
import { api } from '../api';
import { useAuth } from '../contexts/AuthContext';
import PageHero from '../components/PageHero';
import Loading from '../components/Loading';
export default function ReviewsPage() {
  const { user } = useAuth(); const [reviews, setReviews] = useState([]); const [products, setProducts] = useState([]); const [form, setForm] = useState({ product: '', rating: 5, text: '' }); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const load = () => Promise.all([api('/reviews'), api('/products?limit=100')]).then(([r,p]) => { setReviews(r.reviews); setProducts(p.products); if (!form.product && p.products[0]) setForm((old) => ({ ...old, product: p.products[0]._id })); }).finally(() => setLoading(false));
  useEffect(() => { load(); }, []);
  const submit = async (event) => { event.preventDefault(); setMessage(''); setError(''); try { const data = await api('/reviews', { method: 'POST', body: form }); setMessage(data.message); setForm((old) => ({ ...old, rating: 5, text: '' })); } catch (e) { setError(e.message); } };
  return <><PageHero eyebrow="REAL DATABASE RECORDS" title="Customer reviews" text="Approved reviews are public. Logged-in customers can submit feedback for administrator moderation." /><section className="section"><div className="container reviews-layout"><div><h2>Approved feedback</h2>{loading ? <Loading /> : <div className="review-list">{reviews.map((review) => <article key={review._id} className="review-list-card"><div className="stars">{'★'.repeat(review.rating)}{'☆'.repeat(5-review.rating)}</div><p>“{review.text}”</p><strong>{review.name}</strong><span>{review.product?.name}</span></article>)}</div>}</div><aside className="form-card"><h2>Write a review</h2>{user ? <form onSubmit={submit}><label>Product<select value={form.product} onChange={(e) => setForm({ ...form, product: e.target.value })}>{products.map((product) => <option key={product._id} value={product._id}>{product.name}</option>)}</select></label><label>Rating<select value={form.rating} onChange={(e) => setForm({ ...form, rating: Number(e.target.value) })}>{[5,4,3,2,1].map((rating) => <option key={rating} value={rating}>{rating} star{rating > 1 ? 's' : ''}</option>)}</select></label><label>Review<textarea rows="6" minLength="10" maxLength="1000" required value={form.text} onChange={(e) => setForm({ ...form, text: e.target.value })} /></label>{message && <div className="alert success">{message}</div>}{error && <div className="alert error">{error}</div>}<button className="button primary full" type="submit">Submit for moderation</button></form> : <div className="empty-state compact"><p>Please log in before submitting a review.</p><a className="button secondary" href="/login">Login</a></div>}</aside></div></section></>;
}
