import { useState } from 'react';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import PageHero from '../components/PageHero';
export default function SignupPage() {
  const { user, signup } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ fullName: '', email: '', phone: '', password: '', confirmPassword: '' }); const [accepted, setAccepted] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  if (user) return <Navigate to="/account" replace />;
  const submit = async (event) => { event.preventDefault(); if (form.password !== form.confirmPassword) return setError('Passwords do not match.'); if (!accepted) return setError('Please confirm that this is a demonstration account.'); setBusy(true); setError(''); try { await signup({ fullName: form.fullName, email: form.email, phone: form.phone, password: form.password }); navigate('/account'); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  return <><PageHero eyebrow="NEW CUSTOMER" title="Create your StyleHaven account" text="Registration creates a related customer record with a unique customer ID and bcrypt-hashed password." compact /><section className="section"><div className="container narrow"><form className="form-card" onSubmit={submit}><div className="form-grid"><label>Full name<input required minLength="2" maxLength="100" autoComplete="name" value={form.fullName} onChange={(e) => setForm({ ...form, fullName: e.target.value })} /></label><label>Phone<input autoComplete="tel" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></label><label className="span-2">Email address<input type="email" required autoComplete="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>Password<input type="password" required minLength="8" autoComplete="new-password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /><small>At least 8 characters with letters and a number.</small></label><label>Confirm password<input type="password" required minLength="8" autoComplete="new-password" value={form.confirmPassword} onChange={(e) => setForm({ ...form, confirmPassword: e.target.value })} /></label></div><label className="checkbox-line"><input type="checkbox" checked={accepted} onChange={(e) => setAccepted(e.target.checked)} /> I understand this is an academic demonstration store and no real payment will be collected.</label>{error && <div className="alert error">{error}</div>}<button className="button primary full" disabled={busy} type="submit">{busy ? 'Creating account…' : 'Create account'}</button><p>Already registered? <Link to="/login">Login</Link></p></form></div></section></>;
}
