const express = require('express');
const mongoose = require('mongoose');
const Product = require('../models/Product');
const Category = require('../models/Category');
const asyncHandler = require('../utils/asyncHandler');
const { allowRoles } = require('../middleware/auth');
const { booleanValue } = require('../utils/helpers');
const router = express.Router();
function slugify(value){return String(value||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
function escapeRegex(value){return String(value||'').replace(/[.*+?^${}()|[\]\\]/g,'\\$&');}
function stringArray(value,fallback=[]){if(value===undefined)return fallback;const list=Array.isArray(value)?value:String(value||'').split(',');return [...new Set(list.map((item)=>String(item).trim()).filter(Boolean))];}
function parseVariants(value,fallback=[]){if(value===undefined)return fallback;const list=Array.isArray(value)?value:[];return list.map((item,index)=>({variantKey:String(item.variantKey||`${item.size}|${item.color}`).trim(),sku:String(item.sku||`VAR-${index+1}`).trim().toUpperCase(),size:String(item.size||'').trim(),color:String(item.color||'').trim(),stock:Number(item.stock),soldQuantity:Number(item.soldQuantity||0)}));}
function optionalNumber(value,fallback=null){if(value===undefined)return fallback;if(value===''||value===null)return null;const parsed=Number(value);return Number.isFinite(parsed)&&parsed>=0?parsed:null;}
function requiredString(value,min,max){const text=String(value||'').trim();return text.length>=min&&text.length<=max;}
function productPayload(body,existing={}){
  const name=body.name!==undefined?String(body.name).trim():existing.name;
  const variants=parseVariants(body.variants,existing.variants||[]);
  const sizes=stringArray(body.sizes,variants.map((v)=>v.size).filter(Boolean));
  const colors=stringArray(body.colors,variants.map((v)=>v.color).filter(Boolean));
  const stock=variants.length?variants.reduce((sum,v)=>sum+(Number.isInteger(v.stock)&&v.stock>=0?v.stock:0),0):(body.stock!==undefined?Number(body.stock):existing.stock);
  const soldQuantity=variants.length?variants.reduce((sum,v)=>sum+(Number.isInteger(v.soldQuantity)&&v.soldQuantity>=0?v.soldQuantity:0),0):(body.soldQuantity!==undefined?Number(body.soldQuantity):existing.soldQuantity||0);
  return {sku:body.sku!==undefined?String(body.sku).trim().toUpperCase():existing.sku,name,slug:body.slug?slugify(body.slug):(name?slugify(name):existing.slug),category:body.category!==undefined?body.category:existing.category,audience:body.audience!==undefined?body.audience:existing.audience||'unisex',tag:body.tag!==undefined?String(body.tag).trim():existing.tag,brand:body.brand!==undefined?String(body.brand).trim():existing.brand,material:body.material!==undefined?String(body.material).trim():existing.material,description:body.description!==undefined?String(body.description).trim():existing.description,careInstructions:body.careInstructions!==undefined?String(body.careInstructions).trim():existing.careInstructions,price:body.price!==undefined?optionalNumber(body.price):existing.price,oldPrice:body.oldPrice===''||body.oldPrice===null?null:(body.oldPrice!==undefined?optionalNumber(body.oldPrice):existing.oldPrice),image:body.image!==undefined?String(body.image).trim():existing.image,gallery:stringArray(body.gallery,existing.gallery||[]),sizes,colors,variants,ratingAverage:body.ratingAverage!==undefined?Number(body.ratingAverage):existing.ratingAverage||0,ratingCount:body.ratingCount!==undefined?Number(body.ratingCount):existing.ratingCount||0,stock,soldQuantity,lowStockThreshold:body.lowStockThreshold!==undefined?Number(body.lowStockThreshold):existing.lowStockThreshold||8,featured:body.featured!==undefined?booleanValue(body.featured):existing.featured||false,status:body.status!==undefined?body.status:existing.status||'active'};
}
function validatePayload(payload){
  if(!requiredString(payload.sku,3,40))return'SKU is required.';if(!requiredString(payload.name,2,140))return'Product name must contain 2 to 140 characters.';if(!requiredString(payload.description,5,1200))return'Description must contain 5 to 1200 characters.';if(!requiredString(payload.image,3,250))return'A product image filename is required.';if(payload.price===null||payload.price===undefined)return'Price must be zero or greater.';if(!mongoose.isValidObjectId(payload.category))return'A valid category is required.';if(!['women','men','unisex'].includes(payload.audience))return'Audience must be women, men or unisex.';if(!Array.isArray(payload.variants)||payload.variants.length<1)return'At least one size and colour variant is required.';
  const keys=new Set();const skus=new Set();for(const variant of payload.variants){if(!requiredString(variant.size,1,30)||!requiredString(variant.color,1,40))return'Each variant requires a size and colour.';if(!Number.isInteger(variant.stock)||variant.stock<0||!Number.isInteger(variant.soldQuantity)||variant.soldQuantity<0)return'Variant stock and sold quantities must be non-negative whole numbers.';const key=`${variant.size}|${variant.color}`.toLowerCase();if(keys.has(key))return'Duplicate size and colour variants are not allowed.';keys.add(key);if(skus.has(variant.sku))return'Duplicate variant SKUs are not allowed.';skus.add(variant.sku);}
  for(const[label,value]of[['Stock',payload.stock],['Sold quantity',payload.soldQuantity],['Low stock threshold',payload.lowStockThreshold],['Rating count',payload.ratingCount]])if(!Number.isInteger(value)||value<0)return`${label} must be a non-negative whole number.`;if(!Number.isFinite(payload.ratingAverage)||payload.ratingAverage<0||payload.ratingAverage>5)return'Average rating must be between 0 and 5.';return null;
}
router.get('/',asyncHandler(async(req,res)=>{const page=Math.max(1,Number.parseInt(req.query.page,10)||1);const limit=Math.min(100,Math.max(1,Number.parseInt(req.query.limit,10)||24));const filter={};const includeInactive=req.user?.role==='admin'&&booleanValue(req.query.includeInactive);if(!includeInactive)filter.status='active';else if(req.query.status)filter.status=req.query.status;if(req.query.category){const category=mongoose.isValidObjectId(req.query.category)?await Category.findById(req.query.category).lean():await Category.findOne({slug:String(req.query.category).toLowerCase()}).lean();if(!category)return res.json({products:[],pagination:{page,limit,total:0,pages:0}});filter.category=category._id;}if(req.query.brand)filter.brand=new RegExp(`^${escapeRegex(req.query.brand)}$`,'i');if(req.query.audience)filter.audience=req.query.audience;if(req.query.featured!==undefined)filter.featured=booleanValue(req.query.featured);if(req.query.search){const term=escapeRegex(req.query.search);filter.$or=[{name:new RegExp(term,'i')},{description:new RegExp(term,'i')},{tag:new RegExp(term,'i')},{sku:new RegExp(term,'i')},{brand:new RegExp(term,'i')},{material:new RegExp(term,'i')},{colors:new RegExp(term,'i')}];}const sortMap={priceAsc:{price:1},priceDesc:{price:-1},nameAsc:{name:1},ratingDesc:{ratingAverage:-1},newest:{createdAt:-1},stockAsc:{stock:1}};const sort=sortMap[req.query.sort]||{featured:-1,createdAt:-1};const[products,total,brands]=await Promise.all([Product.find(filter).populate('category','name slug').sort(sort).skip((page-1)*limit).limit(limit).lean(),Product.countDocuments(filter),Product.distinct('brand',{status:'active'})]);return res.json({products,brands:brands.sort(),pagination:{page,limit,total,pages:Math.ceil(total/limit)}});}));
router.get('/:identifier',asyncHandler(async(req,res)=>{const query=mongoose.isValidObjectId(req.params.identifier)?{_id:req.params.identifier}:{slug:req.params.identifier.toLowerCase()};if(req.user?.role!=='admin')query.status='active';const product=await Product.findOne(query).populate('category','name slug description').lean();if(!product)return res.status(404).json({message:'Product not found.'});return res.json({product});}));
router.post('/',allowRoles('admin'),asyncHandler(async(req,res)=>{const payload=productPayload(req.body||{},{variants:[],sizes:[],colors:[],gallery:[],featured:false,status:'active',lowStockThreshold:8,brand:'StyleHaven',audience:'unisex',soldQuantity:0,ratingAverage:0,ratingCount:0});const error=validatePayload(payload);if(error)return res.status(400).json({message:error});if(!(await Category.exists({_id:payload.category})))return res.status(400).json({message:'Selected category does not exist.'});const product=await Product.create(payload);await product.populate('category','name slug');return res.status(201).json({message:'Product created.',product});}));
router.put('/:id',allowRoles('admin'),asyncHandler(async(req,res)=>{const product=await Product.findById(req.params.id);if(!product)return res.status(404).json({message:'Product not found.'});const payload=productPayload(req.body||{},product.toObject());const error=validatePayload(payload);if(error)return res.status(400).json({message:error});if(!(await Category.exists({_id:payload.category})))return res.status(400).json({message:'Selected category does not exist.'});Object.assign(product,payload);await product.save();await product.populate('category','name slug');return res.json({message:'Product updated.',product});}));
router.delete('/:id',allowRoles('admin'),asyncHandler(async(req,res)=>{const product=await Product.findById(req.params.id);if(!product)return res.status(404).json({message:'Product not found.'});product.status='inactive';await product.save();return res.json({message:'Product deactivated.',product});}));
module.exports=router;
