const fs=require('fs');const path=require('path');const crypto=require('crypto');
const root=path.join(__dirname,'../../..');const databaseDir=path.join(root,'database');const imagesDir=path.join(root,'client/public/images');
const requiredFiles=['README.md','START_HERE.txt','TESTING_CHECKLIST.md','SUBMISSION_CHECKLIST.md','package.json','.env.example','client/package.json','server/package.json','server/.env.example','database/README.md','docs/DATABASE_DESIGN.md','docs/API_REFERENCE.md','docs/ASSESSMENT_MAPPING.md','docs/D1_TO_D2_MAPPING.md','docs/DEPLOYMENT.md'];
const files=['users.json','categories.json','products.json','coupons.json','orders.json','reviews.json','contactmessages.json','newsletters.json'];let errors=[];function check(condition,message){if(!condition)errors.push(message);}function readJson(file){try{return JSON.parse(fs.readFileSync(path.join(databaseDir,file),'utf8'));}catch(error){errors.push(`${file}: ${error.message}`);return[];}}
for(const file of requiredFiles)check(fs.existsSync(path.join(root,file)),`Missing required file: ${file}`);const data=Object.fromEntries(files.map(file=>[file,readJson(file)]));const oid=/^[a-f0-9]{24}$/i;
for(const[file,records]of Object.entries(data)){check(Array.isArray(records),`${file} must contain a JSON array.`);const ids=new Set();for(const record of records){check(oid.test(String(record._id)),`${file} has invalid _id ${record._id}`);check(!ids.has(record._id),`${file} has duplicate _id ${record._id}`);ids.add(record._id);}}
const users=new Set(data['users.json'].map(r=>r._id));const categories=new Set(data['categories.json'].map(r=>r._id));const products=new Map(data['products.json'].map(r=>[r._id,r]));
check(data['categories.json'].length>=4,'Expected at least four populated clothing collections.');check(data['products.json'].length>=24,'Expected extensive clothing product population.');
for(const category of data['categories.json'])check(fs.existsSync(path.join(imagesDir,category.image)),`Missing category image: ${category.image}`);
const productSkus=new Set(),productSlugs=new Set(),variantSkus=new Set();
for(const p of products.values()){check(categories.has(p.category),`Product ${p.sku} references a missing category.`);check(Number.isInteger(p.stock)&&p.stock>=0,`Product ${p.sku} has invalid stock.`);check(Number(p.price)>=0,`Product ${p.sku} has invalid price.`);check(Array.isArray(p.sizes)&&p.sizes.length>0,`Product ${p.sku} requires sizes.`);check(Array.isArray(p.colors)&&p.colors.length>0,`Product ${p.sku} requires colours.`);check(Array.isArray(p.variants)&&p.variants.length>0,`Product ${p.sku} requires variants.`);let variantStock=0,variantSold=0;const keys=new Set();for(const v of p.variants||[]){check(v.size&&v.color,`Product ${p.sku} has an incomplete variant.`);check(Number.isInteger(v.stock)&&v.stock>=0,`Product ${p.sku} variant has invalid stock.`);check(Number.isInteger(v.soldQuantity)&&v.soldQuantity>=0,`Product ${p.sku} variant has invalid sold quantity.`);const key=`${v.size}|${v.color}`.toLowerCase();check(!keys.has(key),`Product ${p.sku} has duplicate variant ${key}.`);keys.add(key);check(!variantSkus.has(v.sku),`Duplicate variant SKU ${v.sku}`);variantSkus.add(v.sku);variantStock+=v.stock;variantSold+=v.soldQuantity;}check(variantStock===p.stock,`Product ${p.sku} aggregate stock differs from variants.`);check(variantSold===p.soldQuantity,`Product ${p.sku} aggregate sold quantity differs from variants.`);check(Number(p.ratingAverage)>=0&&Number(p.ratingAverage)<=5,`Product ${p.sku} has invalid rating.`);check(!productSkus.has(p.sku),`Duplicate product SKU ${p.sku}`);productSkus.add(p.sku);check(!productSlugs.has(p.slug),`Duplicate product slug ${p.slug}`);productSlugs.add(p.slug);check(fs.existsSync(path.join(imagesDir,p.image)),`Missing product image: ${p.image}`);}
const emails=new Set();for(const u of data['users.json']){check(!emails.has(u.email),`Duplicate user email ${u.email}`);emails.add(u.email);check(/^\$2[aby]\$/.test(u.password),`User ${u.email} password is not bcrypt-hashed.`);for(const productId of u.wishlist||[])check(products.has(productId),`User ${u.email} wishlist references a missing product.`);}
const orderRefs=new Set();for(const o of data['orders.json']){check(users.has(o.customer),`Order ${o.orderReference} references a missing customer.`);check(!orderRefs.has(o.orderReference),`Duplicate order reference ${o.orderReference}`);orderRefs.add(o.orderReference);check(Array.isArray(o.items)&&o.items.length>0,`Order ${o.orderReference} contains no items.`);let subtotal=0;for(const item of o.items||[]){const p=products.get(item.product);check(Boolean(p),`Order ${o.orderReference} references a missing product.`);if(p)check((p.variants||[]).some(v=>v.size===item.size&&v.color===item.color),`Order ${o.orderReference} references a missing size/colour variant.`);subtotal+=Number(item.lineTotal||0);}check(Math.abs(subtotal-Number(o.subtotal))<0.02,`Order ${o.orderReference} subtotal is inconsistent.`);check(Math.abs((Number(o.subtotal)+Number(o.deliveryFee)-Number(o.discount))-Number(o.total))<0.02,`Order ${o.orderReference} total is inconsistent.`);}
for(const r of data['reviews.json']){check(!r.customer||users.has(r.customer),`Review ${r._id} references a missing customer.`);check(!r.product||products.has(r.product),`Review ${r._id} references a missing product.`);}for(const m of data['contactmessages.json'])check(!m.customer||users.has(m.customer),`Contact message ${m._id} references a missing customer.`);
const forbiddenNames=['.env','node_modules','.git'];function walk(dir){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){if(forbiddenNames.includes(entry.name))errors.push(`Forbidden submission item: ${path.relative(root,path.join(dir,entry.name))}`);if(entry.isDirectory()&&!forbiddenNames.includes(entry.name))walk(path.join(dir,entry.name));}}walk(root);
const forbiddenProjectTerms=['mobi'+'hub','urban'+'thread','medi'+'care','libra'+'track','book'+'nest','fit'+'zone','active'+'gear','splash'+'pro','stationary'+'mart'];function scanText(dir){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){if(['node_modules','.git'].includes(entry.name))continue;const full=path.join(dir,entry.name);if(entry.isDirectory())scanText(full);else if(/\.(?:js|jsx|json|md|txt|html|css|example)$/i.test(entry.name)||entry.name==='package.json'){const text=fs.readFileSync(full,'utf8').toLowerCase();for(const term of forbiddenProjectTerms)check(!text.includes(term),`Unrelated project term ${term} found in ${path.relative(root,full)}`);}}}scanText(root);
const digest=crypto.createHash('sha256').update(JSON.stringify(data)).digest('hex').slice(0,12);if(errors.length){console.error(`Submission validation failed with ${errors.length} issue(s):`);errors.forEach(error=>console.error(`- ${error}`));process.exit(1);}console.log('StyleHaven submission data validation passed.');console.log(`Records: users=${data['users.json'].length}, categories=${data['categories.json'].length}, products=${data['products.json'].length}, orders=${data['orders.json'].length}, reviews=${data['reviews.json'].length}`);console.log(`Data digest: ${digest}`);
